name: Build File Tree Generator
on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main, master ]
jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Update version info
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        $VersionNumber = "${{ github.ref }}".Substring(11)  # Extract version from tag
        (Get-Content src/update_checker.py) -replace 'CURRENT_VERSION = ".*"', "CURRENT_VERSION = ""$VersionNumber""" | Set-Content src/update_checker.py
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=resources/icon.ico --name FileTreeGenerator src/file_tree_gui.py
    
    - name: Create Inno Setup installer
      run: |
        # Download and install Inno Setup
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process -FilePath "is.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
        
        # Compile installer
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup_script.iss
      
    - name: Upload exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: FileTreeGenerator.exe
        path: dist/FileTreeGenerator.exe
        
    - name: Upload installer artifact
      uses: actions/upload-artifact@v3
      with:
        name: FileTreeGenerator_Setup.exe
        path: installer/FileTreeGenerator_Setup.exe
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/FileTreeGenerator.exe
          installer/FileTreeGenerator_Setup.exe
        draft: false
        prerelease: false